### ISSUE TITLE
Plan to support videojs 7 version?

### ISSUE THREAD

**Issue by mekya** [facundofernandez/videojs-dvr#6]
I've just checked that if it's working for videojs 7.5.5 with [http-streaming plugin](https://github.com/videojs/http-streaming). It has some issues with that. 

Do you plan to support videojs 7?

Thank you for your great work

**Comment by facundofernandez** [comment]
Hi mekya, today I uploaded a new version with support for videojs with http-streaming plugin.

Thanks for your support.
